window.INSIGNIA_DATA = {
  "meta": {
    "generated_at": "2026-10-06",
    "note": "Panel gotowy. Kolejne runy trackera mają aktualizować ten plik z repozytorium."
  },
  "listings": [
    {
      "key":"ID6HYQae",
      "portal":"otomoto/olx",
      "portal_id":"ID6HYQae / OLX1065759276",
      "vin":"W0VZT8EB7J1128163",
      "title":"2018 Opel Insignia B Sports Tourer 1.5T 165",
      "price_pln":60000,
      "year":2018,
      "mileage_km":124000,
      "gearbox":"automatic",
      "status":"sold",
      "problematic":false,
      "first_seen":"2026-10-02",
      "last_seen":"2026-10-05",
      "equipment":{"heated_seats":true,"heated_steering":true,"heated_windshield":true,"rear_camera":true,"hud":true,"carplay":true,"android_auto":true,"electric_tailgate":true,"handsfree_tailgate":true,"keyless":true,"park_assist":true,"rcta":true},
      "seller_claims":["sprzedaż potwierdzona przez użytkownika"]
    },
    {
      "key":"ID6Ifr03",
      "portal":"otomoto",
      "portal_id":"ID6Ifr03",
      "title":"2017 Opel Insignia B Sports Tourer 1.5T 165",
      "price_pln":38400,
      "year":2017,
      "mileage_km":151600,
      "gearbox":"automatic",
      "status":"active",
      "problematic":true,
      "first_seen":"2026-10-06",
      "last_seen":"2026-10-06",
      "equipment":{"intellilux":true,"hud":true,"acc":true,"rear_camera":true,"carplay":true,"android_auto":true,"heated_seats":true,"heated_steering":true},
      "seller_claims":["kopci na biało po rozgrzaniu","nowe turbo i rozrząd wg sprzedawcy"]
    },
    {
      "key":"ID6IgSC6",
      "portal":"otomoto",
      "portal_id":"ID6IgSC6",
      "title":"2019 Opel Insignia B Sports Tourer 1.5T 165",
      "price_pln":56000,
      "year":2019,
      "mileage_km":94586,
      "gearbox":"automatic",
      "status":"active",
      "problematic":false,
      "first_seen":"2026-10-06",
      "last_seen":"2026-10-06",
      "equipment":{"heated_seats":true,"heated_steering":true,"heated_windshield":true,"rear_camera":true,"blind_spot":true,"rcta":true,"keyless":true,"traffic_signs":true,"carplay":true,"android_auto":true},
      "seller_claims":["Polska","pierwszy właściciel","bezwypadkowy i ASO wg pól ogłoszenia"],
      "url":"https://www.otomoto.pl/osobowe/oferta/opel-insignia-ID6IgSC6.html"
    },
    {
      "key":"ID6IgRUS",
      "portal":"otomoto",
      "portal_id":"ID6IgRUS",
      "title":"2018 Opel Insignia B Sports Tourer 1.5T 165",
      "price_pln":43900,
      "year":2018,
      "mileage_km":172916,
      "gearbox":"automatic",
      "status":"active",
      "problematic":false,
      "first_seen":"2026-10-06",
      "last_seen":"2026-10-06",
      "equipment":{"heated_seats":true,"heated_steering":true,"rear_camera":true,"hud":true,"intellilux":true,"electric_tailgate":true,"handsfree_tailgate":true,"keyless":true,"carplay":true,"android_auto":true},
      "seller_claims":["Niemcy","bezwypadkowy/ASO wg pól"],
      "url":"https://www.otomoto.pl/osobowe/oferta/opel-insignia-ID6IgRUS.html"
    },
    {
      "key":"ID6IgS6W",
      "portal":"otomoto",
      "portal_id":"ID6IgS6W",
      "vin":"W0VZS8GK4K1011772",
      "title":"2018 Opel Insignia B Sports Tourer 1.6T 200",
      "price_pln":53900,
      "year":2018,
      "mileage_km":160000,
      "gearbox":"manual",
      "status":"active",
      "problematic":false,
      "first_seen":"2026-10-06",
      "last_seen":"2026-10-06",
      "equipment":{"panorama":true,"carplay":true,"android_auto":true,"keyless":true,"rear_camera":true,"heated_seats":true,"heated_steering":true,"heated_windshield":true,"acc":true,"traffic_signs":true},
      "seller_claims":["import","deklarowane ASO i bezwypadkowość"],
      "url":"https://www.otomoto.pl/osobowe/oferta/opel-insignia-ID6IgS6W.html"
    },
    {
      "key":"ID6I9Thl",
      "portal":"otomoto",
      "portal_id":"ID6I9Thl",
      "title":"2020 Opel Insignia B Sports Tourer 1.5T 165",
      "price_pln":62900,
      "year":2020,
      "mileage_km":83406,
      "gearbox":"automatic",
      "status":"active",
      "problematic":false,
      "first_seen":"2026-10-04",
      "last_seen":"2026-10-06",
      "equipment":{"heated_seats":true,"heated_steering":true,"traffic_signs":true}
    }
  ],
  "events": [
    {"at":"2026-10-05","type":"sold","portal":"otomoto/olx","portal_id":"ID6HYQae","price_pln":60000},
    {"at":"2026-10-06","type":"first_seen","portal":"otomoto","portal_id":"ID6IgSC6","price_pln":56000},
    {"at":"2026-10-06","type":"first_seen","portal":"otomoto","portal_id":"ID6IgRUS","price_pln":43900},
    {"at":"2026-10-06","type":"first_seen","portal":"otomoto","portal_id":"ID6IgS6W","price_pln":53900},
    {"at":"2026-10-06","type":"price_down","portal":"otomoto","portal_id":"ID6IgrZC","price_pln":43900}
  ]
};
